Run prettier

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -16,19 +16,19 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: '24'
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '24'
 
-    - name: Install dependencies
-      run: npm ci
+      - name: Install dependencies
+        run: npm ci
 
-    - name: Run unit tests with Jest
-      run: npm test
+      - name: Run unit tests with Jest
+        run: npm test
 
   build-and-push:
     name: Build and Push
@@ -39,81 +39,81 @@ jobs:
       version: ${{ steps.extract_version.outputs.version }}
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - name: Extract version from package.json
-      id: extract_version
-      run: |
-        VERSION=$(jq -r .version package.json)
-        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
-        echo "VERSION=$VERSION" >> "$GITHUB_ENV"
-        echo "Version extracted from package.json: $VERSION"
+      - name: Extract version from package.json
+        id: extract_version
+        run: |
+          VERSION=$(jq -r .version package.json)
+          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
+          echo "Version extracted from package.json: $VERSION"
 
-    - name: Set image namespace variable
-      run: |
-        NAMESPACE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
-        echo "NAMESPACE=$NAMESPACE" >> "$GITHUB_ENV"
-        echo "Namespace: $NAMESPACE"
+      - name: Set image namespace variable
+        run: |
+          NAMESPACE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
+          echo "NAMESPACE=$NAMESPACE" >> "$GITHUB_ENV"
+          echo "Namespace: $NAMESPACE"
 
-    - name: Check if image tag exists on GHCR
-      run: |
-        EXISTS_GHCR=false
-        if docker manifest inspect ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}; then
-          echo "$NAMESPACE/$IMAGE_NAME image tag $VERSION exists on GHCR"
-          EXISTS_GHCR=true
-        fi
-        echo "EXISTS_GHCR=$EXISTS_GHCR" >> $GITHUB_ENV
+      - name: Check if image tag exists on GHCR
+        run: |
+          EXISTS_GHCR=false
+          if docker manifest inspect ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}; then
+            echo "$NAMESPACE/$IMAGE_NAME image tag $VERSION exists on GHCR"
+            EXISTS_GHCR=true
+          fi
+          echo "EXISTS_GHCR=$EXISTS_GHCR" >> $GITHUB_ENV
 
-    - name: Check if image tag exists on Docker Hub
-      run: |
-        EXISTS_DOCKERHUB=false
-        if docker manifest inspect docker.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}; then
-          echo "$NAMESPACE/$IMAGE_NAME image tag $VERSION exists on Docker Hub"
-          EXISTS_DOCKERHUB=true
-        fi
-        echo "EXISTS_DOCKERHUB=$EXISTS_DOCKERHUB" >> $GITHUB_ENV
+      - name: Check if image tag exists on Docker Hub
+        run: |
+          EXISTS_DOCKERHUB=false
+          if docker manifest inspect docker.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}; then
+            echo "$NAMESPACE/$IMAGE_NAME image tag $VERSION exists on Docker Hub"
+            EXISTS_DOCKERHUB=true
+          fi
+          echo "EXISTS_DOCKERHUB=$EXISTS_DOCKERHUB" >> $GITHUB_ENV
 
-    - name: Fail if both DockerHub and GHCR images exist
-      run: |
-        if [ "$EXISTS_GHCR" = "true" ] && [ "$EXISTS_DOCKERHUB" = "true" ]; then
-          echo "Both DockerHub and GHCR image tags exist. Failing the pipeline."
-          exit 1
-        fi
+      - name: Fail if both DockerHub and GHCR images exist
+        run: |
+          if [ "$EXISTS_GHCR" = "true" ] && [ "$EXISTS_DOCKERHUB" = "true" ]; then
+            echo "Both DockerHub and GHCR image tags exist. Failing the pipeline."
+            exit 1
+          fi
 
-    - name: Build docker image
-      run: |
-        docker build -t ${{ env.IMAGE_NAME }}:current .
+      - name: Build docker image
+        run: |
+          docker build -t ${{ env.IMAGE_NAME }}:current .
 
-    - name: Tag docker image
-      run: |
-        docker tag ${{ env.IMAGE_NAME }}:current ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
-        docker tag ${{ env.IMAGE_NAME }}:current ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-        docker tag ${{ env.IMAGE_NAME }}:current ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
-        docker tag ${{ env.IMAGE_NAME }}:current ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+      - name: Tag docker image
+        run: |
+          docker tag ${{ env.IMAGE_NAME }}:current ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
+          docker tag ${{ env.IMAGE_NAME }}:current ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+          docker tag ${{ env.IMAGE_NAME }}:current ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
+          docker tag ${{ env.IMAGE_NAME }}:current ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
 
-    - name: List local docker images
-      run: docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.ID}}\t{{.Size}}"
+      - name: List local docker images
+        run: docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.ID}}\t{{.Size}}"
 
-    - name: Login to GHCR
-      if: env.EXISTS_GHCR != 'true'
-      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+      - name: Login to GHCR
+        if: env.EXISTS_GHCR != 'true'
+        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
-    - name: Push images to GHCR
-      if: env.EXISTS_GHCR != 'true'
-      run: |
-        docker push ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
-        docker push ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+      - name: Push images to GHCR
+        if: env.EXISTS_GHCR != 'true'
+        run: |
+          docker push ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
+          docker push ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
 
-    - name: Login to Docker Hub
-      if: env.EXISTS_DOCKERHUB != 'true'
-      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ env.NAMESPACE }} --password-stdin
+      - name: Login to Docker Hub
+        if: env.EXISTS_DOCKERHUB != 'true'
+        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ env.NAMESPACE }} --password-stdin
 
-    - name: Push images to Docker Hub
-      if: env.EXISTS_DOCKERHUB != 'true'
-      run: |
-        docker push ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
-        docker push ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+      - name: Push images to Docker Hub
+        if: env.EXISTS_DOCKERHUB != 'true'
+        run: |
+          docker push ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
+          docker push ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
 
   create-release:
     name: Create GitHub Release
@@ -121,11 +121,11 @@ jobs:
     needs: build-and-push
 
     steps:
-    - name: Create GitHub Release
-      uses: ncipollo/release-action@v1
-      with:
-        tag: "${{ needs.build-and-push.outputs.version }}"
-        token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
-        generateReleaseNotes: true
-        draft: true
-        prerelease: false
+      - name: Create GitHub Release
+        uses: ncipollo/release-action@v1
+        with:
+          tag: '${{ needs.build-and-push.outputs.version }}'
+          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
+          generateReleaseNotes: true
+          draft: true
+          prerelease: false
